#!/usr/bin/env node
/**
 * Regenerates docs/plan/MAP.md — a pre-computed index of where everything lives.
 *
 * Its whole purpose is token economy: an agent that can look up
 * `model Invoice` or `assertPeriodOpen` in a 900-line table never runs the
 * exploratory grep that dumps half the repo into its context. A stale map is
 * worse than no map, so this runs in CI and the build fails if it drifts.
 *
 *   node scripts/genmap.mjs          # write
 *   node scripts/genmap.mjs --check  # exit 1 if out of date
 */
import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { join, relative } from 'node:path';

const ROOT = process.cwd();
const out = [];
const P = (s) => out.push(s);

function walk(dir, exts, acc = []) {
  if (!existsSync(dir)) return acc;
  for (const e of readdirSync(dir)) {
    if (e === 'node_modules' || e === 'dist' || e === '.git') continue;
    const p = join(dir, e);
    if (statSync(p).isDirectory()) walk(p, exts, acc);
    else if (exts.some((x) => e.endsWith(x))) acc.push(p);
  }
  return acc;
}
const lines = (p) => readFileSync(p, 'utf8').split('\n');
const rel = (p) => relative(ROOT, p).replace(/\\/g, '/');

P('# MAP — where everything is');
P('');
P('> Generated by `node scripts/genmap.mjs`. CI fails if stale.');
P('>');
P('> **Look here before you grep.** An exploratory search on this repo costs more');
P('> than the answer is worth; this table is the answer. Read the exact line range');
P('> you need with `Read offset/limit`, never the whole file.');
P('');

// ---- Prisma models -------------------------------------------------------
const schemaDir = join(ROOT, 'apps/api/prisma');
const schemaFiles = walk(schemaDir, ['.prisma']);
const models = [];
for (const f of schemaFiles) {
  lines(f).forEach((l, i) => {
    const m = l.match(/^model\s+(\w+)\s*\{/);
    if (m) models.push([m[1], `${rel(f)}:${i + 1}`]);
  });
}
models.sort((a, b) => a[0].localeCompare(b[0]));
P(`## Prisma models (${models.length})`);
P('');
P(models.map(([n, at]) => `\`${n}\` ${at}`).join(' · '));
P('');

// ---- Exported symbols ----------------------------------------------------
const srcRoots = [
  ['API domains', 'apps/api/src/domains'],
  ['API platform', 'apps/api/src/platform'],
  ['API imports', 'apps/api/src/imports'],
  ['API jobs / events / agents', 'apps/api/src'],
  ['Shared vocabulary', 'packages/shared/src'],
];
const seen = new Set();
for (const [title, dir] of srcRoots) {
  const files = walk(join(ROOT, dir), ['.ts']).filter((f) => {
    const r = rel(f);
    if (r.includes('/tests/') || r.endsWith('.test.ts')) return false;
    if (title.startsWith('API jobs')) {
      return /\/(jobs|events|agents|lib)\//.test(r) && !seen.has(r);
    }
    return !seen.has(r);
  });
  if (!files.length) continue;
  P(`## ${title}`);
  P('');
  for (const f of files.sort()) {
    seen.add(rel(f));
    const ls = lines(f);
    const syms = [];
    ls.forEach((l, i) => {
      const m = l.match(
        /^export\s+(?:async\s+)?(?:function|const|class|type|interface|enum)\s+(\w+)/
      );
      if (m) syms.push(`${m[1]}:${i + 1}`);
    });
    if (!syms.length) continue;
    P(`**\`${rel(f)}\`** (${ls.length} lines) — ${syms.join(' · ')}`);
    P('');
  }
}

// ---- HTTP routes ---------------------------------------------------------
const routeFiles = walk(join(ROOT, 'apps/api/src/routes'), ['.ts']).sort();
if (routeFiles.length) {
  P('## HTTP routes');
  P('');
  for (const f of routeFiles) {
    const ls = lines(f);
    const rs = [];
    ls.forEach((l, i) => {
      const m = l.match(/\.(get|post|put|patch|delete)\(\s*['"`]([^'"`]+)/);
      if (m) rs.push(`${m[1].toUpperCase()} ${m[2]}:${i + 1}`);
    });
    if (rs.length) {
      P(`**\`${rel(f)}\`** (${ls.length} lines) — ${rs.join(' · ')}`);
      P('');
    }
  }
}

// ---- Web pages -----------------------------------------------------------
const pages = walk(join(ROOT, 'apps/web/src/pages'), ['.tsx']).sort();
if (pages.length) {
  P('## Web pages');
  P('');
  for (const f of pages) {
    const ls = lines(f);
    const ex = [];
    ls.forEach((l, i) => {
      const m = l.match(/^export\s+(?:default\s+)?function\s+(\w+)/);
      if (m) ex.push(`${m[1]}:${i + 1}`);
    });
    P(`**\`${rel(f)}\`** (${ls.length} lines) — ${ex.join(' · ') || 'default export'}`);
    P('');
  }
}

// ---- Never read ----------------------------------------------------------
const big = walk(ROOT, ['.yaml', '.lock', '.json'])
  .filter((f) => !rel(f).includes('node_modules'))
  .map((f) => [rel(f), lines(f).length])
  .filter(([, n]) => n > 800)
  .sort((a, b) => b[1] - a[1]);
if (big.length) {
  P('## Never read whole');
  P('');
  P('Generated or lock files. Nothing in them answers a question worth the tokens.');
  P('');
  for (const [r, n] of big) P(`- \`${r}\` (${n} lines)`);
  P('');
}

const text = out.join('\n');
const target = join(ROOT, 'docs/plan/MAP.md');
if (process.argv.includes('--check')) {
  const cur = existsSync(target) ? readFileSync(target, 'utf8') : '';
  if (cur !== text) {
    console.error('MAP.md is stale. Run: node scripts/genmap.mjs');
    process.exit(1);
  }
  console.log('MAP.md up to date.');
} else {
  writeFileSync(target, text);
  console.log(`MAP.md written: ${models.length} models, ${text.split('\n').length} lines.`);
}
